# PROD DATABASE CONFIG
spring.datasource.username=postgres
spring.datasource.password=2024
# PROD HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# PROD LOGGER CONFIG
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=WARN
logging.file.path=/root/logs_microservices

#and need to validation for using button for Delete from disk or Save to disk the ask as a Modal for enter the Password 
security.save.delete.password=987@321
